#pragma once
#include <I18n.h>
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include "InkMODSettings.h"

enum class BookMenuItemId : uint8_t { FOOTNOTES=0, SELECT_CHAPTER=1, READER_OPTIONS=2, CONTROLS_OPTIONS=3, ROTATE_SCREEN=4, AUTO_PAGE_TURN=5, GO_TO_PERCENT=6, BOOKMARK_TOGGLE=7, VIEW_BOOKMARKS=8, DELETE_BOOKMARKS=9, SCREENSHOT=10, DISPLAY_QR=11, DELETE_STATS=12, DELETE_CACHE=13, RESET_READING_PACE=14, SYNC=15, READING_STATS=16, TOGGLE_COMPLETED=17, DICTIONARY=18, CREATE_CLIPPING=19, VIEW_CLIPPINGS=20, COUNT=21 };
struct BookMenuLayoutEntry { BookMenuItemId id; bool enabled=true; };
inline std::vector<BookMenuItemId> defaultBookMenuOrder(){ return {BookMenuItemId::FOOTNOTES,BookMenuItemId::SELECT_CHAPTER,BookMenuItemId::READER_OPTIONS,BookMenuItemId::CONTROLS_OPTIONS,BookMenuItemId::ROTATE_SCREEN,BookMenuItemId::AUTO_PAGE_TURN,BookMenuItemId::GO_TO_PERCENT,BookMenuItemId::BOOKMARK_TOGGLE,BookMenuItemId::VIEW_BOOKMARKS,BookMenuItemId::DELETE_BOOKMARKS,BookMenuItemId::SCREENSHOT,BookMenuItemId::DISPLAY_QR,BookMenuItemId::DELETE_STATS,BookMenuItemId::DELETE_CACHE,BookMenuItemId::RESET_READING_PACE,BookMenuItemId::SYNC,BookMenuItemId::READING_STATS,BookMenuItemId::TOGGLE_COMPLETED,BookMenuItemId::CREATE_CLIPPING,BookMenuItemId::VIEW_CLIPPINGS,BookMenuItemId::DICTIONARY}; }
inline bool dictionaryLookupAssignedToButton(){ return SETTINGS.shortPwrBtn==InkMODSettings::DICTIONARY_LOOKUP || SETTINGS.longPwrBtn==InkMODSettings::DICTIONARY_LOOKUP || SETTINGS.longPressMenuAction==InkMODSettings::LONG_MENU_DICTIONARY_LOOKUP || SETTINGS.longPressBackAction==InkMODSettings::LONG_MENU_DICTIONARY_LOOKUP; }
inline StrId bookMenuItemLabel(BookMenuItemId id){ switch(id){case BookMenuItemId::FOOTNOTES:return StrId::STR_FOOTNOTES;case BookMenuItemId::SELECT_CHAPTER:return StrId::STR_SELECT_CHAPTER;case BookMenuItemId::READER_OPTIONS:return StrId::STR_READER_OPTIONS;case BookMenuItemId::CONTROLS_OPTIONS:return StrId::STR_CAT_CONTROLS;case BookMenuItemId::ROTATE_SCREEN:return StrId::STR_ORIENTATION;case BookMenuItemId::AUTO_PAGE_TURN:return StrId::STR_AUTO_TURN_INTERVAL_SECONDS;case BookMenuItemId::GO_TO_PERCENT:return StrId::STR_GO_TO_PERCENT;case BookMenuItemId::BOOKMARK_TOGGLE:return StrId::STR_ADD_BOOKMARK;case BookMenuItemId::VIEW_BOOKMARKS:return StrId::STR_VIEW_BOOKMARKS;case BookMenuItemId::DELETE_BOOKMARKS:return StrId::STR_DELETE_BOOKMARKS;case BookMenuItemId::SCREENSHOT:return StrId::STR_SCREENSHOT_BUTTON;case BookMenuItemId::DISPLAY_QR:return StrId::STR_DISPLAY_QR;case BookMenuItemId::DELETE_STATS:return StrId::STR_DELETE_BOOK_STATS;case BookMenuItemId::DELETE_CACHE:return StrId::STR_DELETE_CACHE;case BookMenuItemId::RESET_READING_PACE:return StrId::STR_RESET_READING_PACE;case BookMenuItemId::SYNC:return StrId::STR_SYNC_PROGRESS;case BookMenuItemId::READING_STATS:return StrId::STR_READING_STATS;case BookMenuItemId::TOGGLE_COMPLETED:return StrId::STR_MARK_FINISHED;case BookMenuItemId::DICTIONARY:return StrId::STR_DICTIONARY;case BookMenuItemId::CREATE_CLIPPING:return StrId::STR_CREATE_CLIPPING;case BookMenuItemId::VIEW_CLIPPINGS:return StrId::STR_CLIPPINGS;default:return StrId::STR_NONE_OPT;} }
inline std::vector<BookMenuLayoutEntry> loadBookMenuLayout(){ auto d=defaultBookMenuOrder(); std::vector<BookMenuLayoutEntry> r; bool seen[(size_t)BookMenuItemId::COUNT]={}; const char* p=SETTINGS.bookMenuLayout; while(p&&*p){ while(*p==','||isspace((unsigned char)*p))++p; bool en=true; if(*p=='!'){en=false;++p;} char* e=nullptr; long v=strtol(p,&e,10); if(e==p)break; p=e; if(v>=0&&v<(long)BookMenuItemId::COUNT&&!seen[v]){seen[v]=true;r.push_back({(BookMenuItemId)v,en});} while(*p&&*p!=',')++p; } for(auto id:d) if(!seen[(size_t)id]) r.push_back({id,true}); return r; }
inline bool saveBookMenuLayout(const std::vector<BookMenuLayoutEntry>& l){ std::string o; for(size_t i=0;i<l.size();++i){if(i)o+=',';if(!l[i].enabled)o+='!';o+=std::to_string((unsigned)l[i].id);} if(o.size()>=sizeof(SETTINGS.bookMenuLayout))return false; strncpy(SETTINGS.bookMenuLayout,o.c_str(),sizeof(SETTINGS.bookMenuLayout)-1);SETTINGS.bookMenuLayout[sizeof(SETTINGS.bookMenuLayout)-1]='\0';return SETTINGS.saveToFile(); }
